version: "3.9"
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: next-client
    volumes:
      - /app/node_modules
      - ./client:/app
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    container_name: nest-api
    volumes:
      - /app/node_modules
      - ./api:/app
  postgres:
    image: postgres:13
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    env_file:
      - ./api/.env/
    volumes:
      - postgres:/var/lib/postgresql/data
  nginx:
    depends_on:
      - client
      - api
    restart: always
    build:
      context: ./api/docker/nginx/
      dockerfile: Dockerfile
    ports:
      - "3050:80"
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: swagger_ui_container
    ports:
      - "50:5050"
    volumes:
      - ./doc:/usr/share/nginx/html/doc
    environment:
      API_URL: doc/openapi.yaml
volumes:
  postgres:
    name: nest-prisma-docker-db
